### ISSUE TITLE
Implement error checking in the form of exceptions

### ISSUE THREAD

**Issue by VRushLP** [VRushLP/TCSS360Brooklyn#31]
ex: 
//In ParkManagerDriver
try
{
Calendar.addJob(j)
}
catch (JobTimeTravelException e)
{
System.out.println(e.errorMessage);
}

**Comment by VRushLP** [comment]
This seems to be mostly in for now, and we can always add more kinds of exceptions in later if I missed any.

**Comment by b3astman** [comment]
Additional error checking that still needs to be implemented:
- when editing a job, make sure that a light + medium + difficult max volunteers never exceeds the 30 at any time. Otherwise, throw JobIsFullException? 

*will edit & add to later if I discover more

**Comment by VRushLP** [comment]
JobIsFull is intended for when you attempt to sign up for a Job and it already has the maximum number of volunteers.
A new exception would probably work better.
It'd also mean we can stop error checking like we are now with max volunteers, which is sort of a mishmash
*Apparently ctrl-enter automatically comments

**Comment by b3astman** [comment]
We could create ExceedsMaximumVolunteerCountException for this? or something similar.

**Comment by VRushLP** [comment]
Yeah, that sounds good.
