### ISSUE TITLE
Null pointer exception when printing jobs for volunteer in driver

### ISSUE THREAD

**Issue by b3astman** [VRushLP/TCSS360Brooklyn#58]

**Comment by VRushLP** [comment]
Can you explain this bug? I'm not able to replicate it.

**Comment by b3astman** [comment]
Maybe it is just in my branch. I believe when trying to view jobs a volunteer has signed up for, a null pointer exception would be thrown, which doesn't seem possible since it just prints with a for each loop on an arraylist. I am not in front if my code right now but I can check it out again later. Sorry!
