### ISSUE TITLE
Document pre conditions and post conditions

### ISSUE THREAD

**Issue by b3astman** [VRushLP/TCSS360Brooklyn#60]
Using @ throws , @ return, and discussing preconditions on parameters in our documentation

**Comment by b3astman** [comment]
I figure this will be one of the last things we do (complete all documentation)

**Comment by VRushLP** [comment]
I'll handle the documentation for the UrbanParkCalendar when I do the tests.

**Comment by ldimov93** [comment]
And I can do the pre and post conditions for methods in Park and/or Park Manager.
