### ISSUE TITLE
Bug: Serialization does not work correctly with Job Categories

### ISSUE THREAD

**Issue by VRushLP** [VRushLP/TCSS360Brooklyn#68]

**Comment by VRushLP** [comment]
After testing for a while, this bug is a misnomer. Something else is causing Volunteers not to show up in the ParkManagerDriver.

**Comment by b3astman** [comment]
Sorry, so are you saying you don't believe this is a serialization issue? Or are you not sure? Just so I can try to narrow down so I can help figure out a solution.

**Comment by VRushLP** [comment]
It's not an issue between serialization and job categories. The problem appears to be in the park class.

**Comment by VRushLP** [comment]
I think I got it. I'll publish the fix in the 'finalizing' branch by 10:30.
From here, I think it's mostly aesthetic changes and practicing.

EDIT: Essentially, the jobs were being put out to the files correctly, but the parks still had references to the old jobs. As far as I know, Java serializing goes from top to bottom with a "has a" relationship. The logic went something like this:
loginList has a reference to a ParkManager, which has a reference to a park, which has a reference to some jobs. However, the jobs in there were not the same as the ones in the UrbanParkCalendar, which were the ones just updated by a Volunteer signing up for them, since Volunteers do not go through parks first.
Now instead of leaving the jobs in the park as is, we update the Parks to have the jobs that are in the Calendar, which we know to be correct.
